### ISSUE TITLE
All staking, LP tokens, NODE, and xNODE are no longer showing newly accrued rewards.

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/node-dashboard-app#164]
**Describe the bug**

In the last 24-36 hours the web app for staking LP tokens and the NODE tokens has stopped showing accrued rewards. Harvest function stake more tokens and claim functions remain working but no new rewards accrue on any of the staking tabs. 
**To Reproduce**

Visit https://app.dappnode.io/ connect a wallet that is staking any tokens, LP for sushi swap Or uniswap, or NODE on either ETH or xDai chains. Harvest any existing rewards. After claiming/harvesting no more rewards will accrue. 
**Expected behavior**

Rewards should continue to accrue continually at the rate posted on each tab but they do not accrue at all currently. 

**Screenshots**

**DAppNode version:**
N/A

- Package version: 
N/A
- OS: 
All
- Browser 
All
**Additional context**

As has been asked more than once on discord about this issue. Will missed reward accruals be retroactively applied?

**Comment by mgarciate** [comment]
Hi @alexpeterson91 could you check again? Working fine on my browser.

**Comment by alexpeterson91** [comment]
Has been fixed by Lanksi/Eduadiez
