### ISSUE TITLE
The xDai staking card says I have 0... but its a lie!

### ISSUE THREAD

**Issue by GriffGreen** [dappnode/node-dashboard-app#83]
<img width="265" alt="Screen Shot 2021-07-16 at 7 58 07 PM" src="https://user-images.githubusercontent.com/14945613/125989763-1639dcc3-01a8-444b-b563-f548fac849c6.png">

**Comment by alexpeterson91** [comment]
this is the backend and front end not communicating, normal issues happens all the time, also its stale been a year
